CREATE TABLE IF NOT EXISTS entregable_1 (
    baseFeePerGas BIGINT,
    difficulty BIGINT,
    extraData VARCHAR(1000),
    gasLimit BIGINT,
    gasUsed BIGINT,
    hash VARCHAR(1000),
    logsBloom VARCHAR(1000),
    miner VARCHAR(1000),
    mixHash VARCHAR(1000),
    nonce VARCHAR(1000),
    number BIGINT,
    parentHash VARCHAR(1000),
    receiptsRoot VARCHAR(1000),
    sha3Uncles VARCHAR(1000),
    size BIGINT,
    stateRoot VARCHAR(1000),
    timestamp BIGINT,
    totalDifficulty BIGINT,
    transactions VARCHAR(1000),
    transactionsRoot VARCHAR(1000),
    uncles VARCHAR(1000),
    withdrawals VARCHAR(1000),
    withdrawalsRoot VARCHAR(1000)
)